### ISSUE TITLE
Python

### ISSUE THREAD

**Issue by firmai** [TommasoBelluzzo/MisreportingDetector#1]
You will be my hero if you get this into Python. I can help if it is something you are interested in doing.

**Comment by firmai** [comment]
Not just this packages one or two others too, as there is no equivalents, unless you know of some python equivalents?

**Comment by TommasoBelluzzo** [comment]
As far as I know, the majority of my projects (except for SystemicRisk) do not have equivalents around there. I've never planned to port them into other programming languages but I think it may be great. The problem is that I do not really have enough time to achieve this task.
Since this is not a code issue, it may be better to talk about this using private channels (my personal e-mail is available on the GitHub profile).

**Comment by firmai** [comment]
Sure, I will get in touch later this year. Maybe we can get someone to do it as part of a school project. Okay, cheers!
